version: '3'
services:
  server:
    image: qnib/alplain-gocd-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
     - 8153:8153
    volumes:
     - /opt/go-server/artifacts/serverBackups/
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - GOCD_SERVER_CLEAN_WORKSPACE=false
     - GO_SERVER_SYSTEM_PROPERTIES='-Dplugin.cd.go.contrib.elastic-agent.docker-swarm.log.level=debug'
  agent:
    image: qnib/alplain-gocd-agent
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
    environment:
     - GO_SERVER=gocd_server
     - DOCKER_HOST=unix:///var/run/docker.sock
     - GOCD_AGENT_AUTOENABLE_KEY=qnibFTW
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
