version: '3'
services:
  server:
    image: qnib/alplain-gocd-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
     - 8153:8153
    volumes:
     - /Users/ckniep/docker/upstream/plain/alplain-gocd-agent/backups/:/opt/go-server/artifacts/serverBackups/
    environment:
     - GOCD_SERVER_CLEAN_WORKSPACE=false
  agent:
    image: qnib/alplain-gocd-agent
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
    environment:
     - GO_SERVER=gocd_server
     - DOCKER_HOST=unix:///var/run/docker.sock
     - GOCD_AGENT_AUTOENABLE_KEY=qnibFTW
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
