version: '3'
services:
  server:
    image: qnib/alplain-gocd-server:17.9.0@sha256:b158936a3af13ba0a1ef74fd2e97ecbb32b3a8478fe1c8465a6de266c0f96174
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
     - 8153:8153
     - 8154:8154
    volumes:
     - ${PWD}/backups/:/opt/go-server/artifacts/serverBackups/
    environment:
     - GOCD_SERVER_CLEAN_WORKSPACE=false
  agent:
    image: qnib/alplain-gocd-agent:17.9.0-1@sha256:457ad4b35afe68b5506909e2cbf454dfdc2750729fd613e4b1d0693ec8c0a279
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
    environment:
     - GO_SERVER_URL=https://tasks.server:8154/go
     - DOCKER_HOST=unix:///var/run/docker.sock
     - GOCD_AGENT_AUTOENABLE_KEY=qnibFTW
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
